apiVersion: v1
kind: Service
metadata:
  name: forecaster-service
  namespace: forecast
spec:
  selector:
    app: forecaster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
